### PR TITLE
Update backend port to 3030

### LINKED ISSUE #5: Update port number for backend project
Currently backend port uses 3000, which is the same as frontend. For local testing they should differ.

### PR DESCRIPTION
**Pull request by evan89**
Updated backend port to 3030

### CODE REVIEW

**Comment by evan89** [comment]
Backend now uses port 3030
image

**Comment by chriscentenera** [comment]
Closes #5

**Comment by chriscentenera** [comment]
Closes #5

**Review by chriscentenera — APPROVED** [review]
Looks good to me! Approved

**Pull request merged**
